### ISSUE TITLE
which version of tensorflow have you used?

### ISSUE THREAD

**Issue by fanyuzeng** [DidiBear/macn-gym-pathfinding#3]
**My server has something wrong, so I reinstall some software, including tensorflow.
The version of my tf is 1.10.0, but there is attributeError as following:**

/usr/bin/python3.5 /home/cr/pycharmProjects/macn-gym-pathfinding/train.py
/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/tf_inspect.py:75: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  return _inspect.getargspec(target)
Traceback (most recent call last):
  File "/home/cr/pycharmProjects/macn-gym-pathfinding/train.py", line 135, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/cr/pycharmProjects/macn-gym-pathfinding/train.py", line 50, in main
    "hidden_size": FLAGS.hidden_size
  File "/home/cr/pycharmProjects/macn-gym-pathfinding/macn/model.py", line 138, in __init__
    self.dnc_core = DNC(access_config, controller_config, output_size=vin_config.ch_q)
  File "/home/cr/pycharmProjects/macn-gym-pathfinding/macn/dnc/dnc.py", line 64, in __init__
    with self._enter_variable_scope():
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/sonnet/python/modules/base.py", line 577, in _enter_variable_scope
    self._check_same_graph()
  File "/usr/local/lib/python3.5/dist-packages/sonnet/python/modules/base.py", line 274, in _check_same_graph
    with tf.init_scope():
AttributeError: module 'tensorflow' has no attribute 'init_scope'

**How to solve this problem?**

**Comment by fanyuzeng** [comment]
tf1.10.0 has no no attribute 'init_scope',  and I have installed tf1.13 to resolve this issue.
